-- SYS
SELECT*
FROM ALL_USERS;
-- 또는 FROM DBA_USERS;

-- SYS 계정이 사용할 수 있는 모든 테이블 정보를 조회. 
-- + (OWNER가 SCOTT인 테이블 정보만 조회하고 싶다.)
SELECT *
FROM ALL_TABLES
-- 또는 FROM DBA_TABLES;
WHERE OWNER = 'SCOTT';
-- 조건 OWNER가 SCOTT인;
FROM dba_tables;
--
SELECT *
FROM V$RESERVED_WORDS
WHERE keyword = 'DATE';




SELECT *
FROM ALL_TABLES
WHERE TABLE_NAME = 'DUAL';

SELECT *
FROM ARIRANG;

SELECT COUNT(*) COUNT
FROM INSA;


-- PUBLIC 시노님 생성
-- SYNONYM ARIRANG 생성
CREATE PUBLIC SYNONYM arirang
FOR scott.emp;
-- SYNONYM ARIRANG 삭제
-- 형식 : DROP [PUBLIC] SYNONYM synonym명;
DROP PUBLIC SYNONYM arirang;

-- 시노님 조회
SELECT *
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'DUAL';

-- 테이블 조회
SELECT *
FROM DBA_TABLES;
FROM ALL_TABLES;
FROM USER_TABLES;
FROM TABS;
